# Generated by Django 4.2 on 2026-02-13 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='dataset/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_type', models.CharField(blank=True, choices=[('Bitcoin', 'Bitcoin'), ('Ethereum', 'Ethereum')], max_length=20, null=True)),
                ('model_name', models.CharField(choices=[('LSTM', 'LSTM'), ('GRU', 'GRU'), ('CNN', 'CNN'), ('ARIMA', 'ARIMA'), ('QSVM', 'QSVM'), ('QML', 'QML')], max_length=50)),
                ('mae_1day', models.FloatField(blank=True, null=True)),
                ('mae_7day', models.FloatField(blank=True, null=True)),
                ('mae_30day', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('mape', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.dataset')),
            ],
            options={
                'unique_together': {('coin_type', 'model_name')},
            },
        ),
    ]
