# Generated by Django 4.2 on 2026-02-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelmetrics',
            name='model_name',
            field=models.CharField(choices=[('LSTM', 'LSTM'), ('GRU', 'GRU'), ('RF', 'Random Forest'), ('CNN', 'CNN'), ('ARIMA', 'ARIMA'), ('QSVM', 'QSVM'), ('QML', 'QML')], max_length=50),
        ),
    ]
